export const products = [
    {
        id: 0,
        category: "basic",
        name: "-----",
        kcal: 0,
        whey: 0,
        fat: 0,
        carbs: 0,
    },
    {
        id: 1,
        category: "fruits/vegetables",
        name: "frozen strawberries",
        kcal: 35,
        whey: 1,
        fat: 0,
        carbs: 8,
    },
    {
        id: 2,
        category: "fruits/vegetables",
        name: "banana",
        kcal: 89,
        whey: 1,
        fat: 0,
        carbs: 23,
    },
    {
        id: 3,
        category: "fruits/vegetables",
        name: "apple",
        kcal: 57,
        whey: 0,
        fat: 0,
        carbs: 14,
    },
    {
        id: 4,
        category: "whey",
        name: "lean cottage cheese",
        kcal: 83,
        whey: 17,
        fat: 0,
        carbs: 4,
    },
    {
        id: 5,
        category: "carbs",
        name: "oat flakes",
        kcal: 354,
        whey: 12,
        fat: 6,
        carbs: 56,
    },
];