export const products = [
    // all properties counted per 100g of a product
    {
        id: 0,
        category: "basic",
        name: "-----",
        kcal: 0,
        protein: 0,
        fat: 0,
        carbs: 0,
        price: 0,
    },
    {
        id: 1,
        category: "fruits/vegetables",
        name: "frozen strawberries",
        kcal: 35,
        protein: 1,
        fat: 0,
        carbs: 8,
        price: 1.53,
    },
    {
        id: 2,
        category: "fruits/vegetables",
        name: "blueberries",
        kcal: 49,
        protein: 1,
        fat: 0,
        carbs: 9,
        price: 2,
    },
    {
        id: 3,
        category: "fat",
        name: "dark chocolate",
        kcal: 588,
        protein: 10,
        fat: 48,
        carbs: 21,
        price: 9.99,
    },
    {
        id: 4,
        category: "fruits/vegetables",
        name: "banana",
        kcal: 89,
        protein: 1,
        fat: 0,
        carbs: 23,
        price: 0.7,
    },
    {
        id: 5,
        category: "carbs",
        name: "whole grain toast bread",
        kcal: 251,
        protein: 9,
        fat: 2,
        carbs: 45,
        price: 0.64,
    },
    {
        id: 6,
        category: "carbs",
        name: "whole grain tortilla",
        kcal: 297,
        protein: 12,
        fat: 7,
        carbs: 43,
        price: 1.61,
    },
    {
        id: 7,
        category: "fat",
        name: "walnuts",
        kcal: 712,
        protein: 15,
        fat: 69,
        carbs: 4,
        price: 8.5,
    },
    {
        id: 8,
        category: "fruits/vegetables",
        name: "apple",
        kcal: 57,
        protein: 0,
        fat: 0,
        carbs: 14,
        price: 0.6,
    },
    {
        id: 9,
        category: "fruits/vegetables",
        name: "potatoes",
        kcal: 77,
        protein: 2,
        fat: 0,
        carbs: 18,
        price: 0.44,
    },
    {
        id: 10,
        category: "fruits/vegetables",
        name: "onion",
        kcal: 40,
        protein: 1,
        fat: 0,
        carbs: 8,
        price: 0.45,
    },
    {
        id: 11,
        category: "fruits/vegetables",
        name: "carrot",
        kcal: 41,
        protein: 1,
        fat: 0,
        carbs: 10,
        price: 0.4,
    },
    {
        id: 12,
        category: "fruits/vegetables",
        name: "champignons",
        kcal: 17,
        protein: 3,
        fat: 0,
        carbs: 3,
        price: 1.6,
    },
    {
        id: 13,
        category: "fruits/vegetables",
        name: "red pepper",
        kcal: 30,
        protein: 1,
        fat: 0,
        carbs: 7,
        price: 1.7,
    },
    {
        id: 14,
        category: "fruits/vegetables",
        name: "tomatoes",
        kcal: 22,
        protein: 1,
        fat: 0,
        carbs: 4,
        price: 1.5,
    },
    {
        id: 15,
        category: "fruits/vegetables",
        name: "cucumber",
        kcal: 15,
        protein: 1,
        fat: 0,
        carbs: 3,
        price: 0.9,
    },
    {
        id: 16,
        category: "protein",
        name: "turkey fillet ham",
        kcal: 115,
        protein: 19,
        fat: 3,
        carbs: 3,
        price: 4,
    },
    {
        id: 17,
        category: "protein",
        name: "mozzarella light",
        kcal: 157,
        protein: 19,
        fat: 8,
        carbs: 1,
        price: 2.63,
    },
    {
        id: 18,
        category: "fat",
        name: "gouda cheese",
        kcal: 347,
        protein: 26,
        fat: 27,
        carbs: 0,
        price: 3.15,
    },
    {
        id: 19,
        category: "fat",
        name: "cream cheese",
        kcal: 224,
        protein: 8,
        fat: 20,
        carbs: 3,
        price: 2.66,
    },
    {
        id: 20,
        category: "protein",
        name: "minced meat of pork ham",
        kcal: 134,
        protein: 20,
        fat: 5,
        carbs: 1,
        price: 2.4,
    },
    {
        id: 21,
        category: "protein",
        name: "chicken breat fillet",
        kcal: 112,
        protein: 22,
        fat: 3,
        carbs: 0,
        price: 2.49,
    },
    {
        id: 22,
        category: "protein",
        name: "natural skyr",
        kcal: 64,
        protein: 12,
        fat: 0,
        carbs: 4,
        price: 1.6,
    },
    {
        id: 23,
        category: "protein",
        name: "vanilla skyr",
        kcal: 82,
        protein: 10,
        fat: 0,
        carbs: 11,
        price: 1.7,
    },
    {
        id: 24,
        category: "protein",
        name: "lean cottage cheese",
        kcal: 82,
        protein: 17,
        fat: 0,
        carbs: 3,
        price: 1.44,
    },
    {
        id: 25,
        category: "protein",
        name: "milk 2%",
        kcal: 50,
        protein: 3,
        fat: 2,
        carbs: 5,
        price: 0.44,
    },
    {
        id: 26,
        category: "fruits/vegetables",
        name: "green beans",
        kcal: 42,
        protein: 2,
        fat: 0,
        carbs: 7,
        price: 0.89,
    },
    {
        id: 27,
        category: "fruits/vegetables",
        name: "chinese vegetables mix",
        kcal: 28,
        protein: 1,
        fat: 0,
        carbs: 3,
        price: 0.88,
    },
    {
        id: 28,
        category: "fruits/vegetables",
        name: "italian vegetables mix",
        kcal: 42,
        protein: 2,
        fat: 0,
        carbs: 6,
        price: 1.1,
    },
    {
        id: 29,
        category: "fat",
        name: "light mayonnaise",
        kcal: 338,
        protein: 1,
        fat: 33,
        carbs: 8,
        price: 2.33,
    },
    {
        id: 30,
        category: "carbs",
        name: "ketchup",
        kcal: 127,
        protein: 1,
        fat: 0,
        carbs: 28,
        price: 0.85,
    },
    {
        id: 31,
        category: "carbs",
        name: "tomato passata",
        kcal: 36,
        protein: 2,
        fat: 0,
        carbs: 6,
        price: 0.96,
    },
    {
        id: 32,
        category: "carbs",
        name: "whole grain spaghetti",
        kcal: 350,
        protein: 15,
        fat: 3,
        carbs: 62,
        price: 0.92
    },
    {
        id: 33,
        category: "carbs",
        name: "whole grain penne pasta",
        kcal: 350,
        protein: 15,
        fat: 3,
        carbs: 62,
        price: 0.92,
    },
    {
        id: 34,
        category: "carbs",
        name: "long grain jasmine rice",
        kcal: 348,
        protein: 7,
        fat: 1,
        carbs: 78,
        price: 0.82,
    },
    {
        id: 35,
        category: "fat",
        name: "olive oil",
        kcal: 828,
        protein: 0,
        fat: 92,
        carbs: 0,
        price: 4.66,
    },
    {
        id: 36,
        category: "protein",
        name: "eggs (1 egg = 60g, 1 egg = 1.10zł)",
        kcal: 143,
        protein: 13,
        fat: 10,
        carbs: 1,
        price: 1.83,
    },
    {
        id: 37,
        category: "carbs",
        name: "low sugar jam (any fruit)",
        kcal: 133,
        protein: 0,
        fat: 0,
        carbs: 33,
        price: 1.19,
    },
    {
        id: 38,
        category: "fat",
        name: "peanut butter",
        kcal: 603,
        protein: 27,
        fat: 48,
        carbs: 12,
        price: 2.7,
    },
    {
        id: 39,
        category: "carbs",
        name: "oat flakes",
        kcal: 354,
        protein: 12,
        fat: 6,
        carbs: 56,
        price: 0.58,
    },
    {
        id: 40,
        category: "carbs",
        name: "corn flakes",
        kcal: 390,
        protein: 9,
        fat: 2,
        carbs: 83,
        price: 1.2,
    },
    {
        id: 41,
        category: "carbs",
        name: "whole grain flour",
        kcal: 331,
        protein: 13,
        fat: 2,
        carbs: 59,
        price: 0.27,
    },
    {
        id: 42,
        category: "fat",
        name: "coconut flakes",
        kcal: 651,
        protein: 7,
        fat: 61,
        carbs: 7,
        price: 1.9,
    },
    {
        id: 43,
        category: "fruits/vegetables",
        name: "canned corn",
        kcal: 69,
        protein: 3,
        fat: 1,
        carbs: 11,
        price: 1.4,
    },
    {
        id: 44,
        category: "fruits/vegetables",
        name: "canned red beans",
        kcal: 99,
        protein: 7,
        fat: 1,
        carbs: 13,
        price: 1.29,
    },
    {
        id: 45,
        category: "protein",
        name: "cocoa powder",
        kcal: 309,
        protein: 24,
        fat: 11,
        carbs: 13,
        price: 4.5,
    },
    {
        id: 46,
        category: "carbs",
        name: "soy sauce",
        kcal: 27,
        protein: 3,
        fat: 0,
        carbs: 3,
        price: 4.99,
    },
    {
        id: 47,
        category: "protein",
        name: "whey - WPC 82",
        kcal: 391,
        protein: 79,
        fat: 6,
        carbs: 4,
        price: 8.57,
    },
    {
        id: 48,
        category: "protein",
        name: "egg whites (1 egg = 35g egg whites, 1 egg = 1.10zł",
        kcal: 48,
        protein: 11,
        fat: 0,
        carbs: 1,
        price: 1.83,
    },
];